services:
  hyundai-connect:
    build: .
    container_name: hyundai-connect
    restart: unless-stopped
    network_mode: "host"  # <-- DIESE ZEILE HINZUFÜGEN
    volumes:
      # Mappe das Logfile nach außen, damit es nicht verloren geht
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      - TZ=Europe/Vienna # Setze deine Zeitzone für korrekte Log-Zeitstempel